# Data Path Settings
data_root: "data/metaworld"
output_root: "output/metaworld_rewards"
seed: 42

# Collection Settings
rollouts_per_setting: 1
camera_names: ["topview", "corner", "corner2"] # Options: 'topview' 'corner', 'corner2', 'corner3', 'behindGripper', 'gripperPOV'
levels:
  - "expert"
  - "partial"
  - "random"

# Task Descriptions
tasks:
  drawer-open-v3:
    description: "Reach the drawer handle and pull the drawer open fully."
    policy: "SawyerDrawerOpenV3Policy"
  button-press-v3:
    description: "Press the red button down until it is fully depressed."
    policy: "SawyerButtonPressV3Policy"
  peg-insert-side-v3:
    description: "Pick up the green peg and insert it horizontally into the hole on the red side of the brown box."
    policy: "SawyerPegInsertionSideV3Policy"
  pick-place-v3:
    description: "Pick up the block and place it precisely into the target bin."
    policy: "SawyerPickPlaceV3Policy"

# Prompt Template
reward_prompt_template: |
  You are an expert roboticist tasked to predict task completion
  percentages for frames of a robot for the task of {task_description}.
  The task completion percentages are between 0 and 100, where 100
  corresponds to full task completion. We provide several examples of
  the robot performing the task at various stages and their
  corresponding task completion percentages. Note that these frames are
  in random order, so please pay attention to the individual frames
  when reasoning about task completion percentage.

  Initial robot scene: [IMG]
  In the initial robot scene, the task completion percentage is 0.

  Now, for the task of {task_description}, output the task completion
  percentage for the following frames that are presented in random
  order. For each frame, format your response as follow: Frame {i}:
  Frame Description: {}, Task Completion Percentages:{}%

# Experiment Settings
experiment_name: "exp1.1"
views: ["topview"]
frames_in_context: 30